import { z } from 'zod';
import { ClaimExtractionSchema } from '@refund/shared';
import { breakerConfig } from '../config/env.js';
import { ModelCircuitBreaker, runCandidates, unavailableFrom, type AttemptOutcome } from './breaker.js';
import { fallbackModels, type Env, type ProviderPreset } from '../config/env.js';
import { redactSecrets } from '../lib/redact.js';
import { buildCaseSummaryUser, buildIntakeUser, CASE_SUMMARY_SYSTEM, CHAT_SYSTEM_PROMPT, INTAKE_SYSTEM } from './prompts.js';
import { AskItemsSchema, CaseSummarySchema, CompleteSchema, IntakeOutputSchema, type IntakeOutput } from './schemas.js';
import { parseJson } from './json.js';
import {
  AiUnavailableError,
  type AIAnalyzer,
  type IntakeInput,
  type CaseSummaryInput,
  type IntakeExit,
  type IntakeReply,
  type AttemptObserver,
  type ChatInput,
  type ChatReply,
} from './analyzer.js';

/**
 * The Anthropic adapter.
 *
 * It exists because Anthropic has no OpenAI-compatible endpoint. `POST
 * /v1/chat/completions` is not served by `api.anthropic.com`, so pointing the
 * OpenAI client at it produces a 404 on a URL that is not wrong so much as
 * inoffensible - and a 404 reads, to everyone except the person who wrote this
 * comment, exactly like an invalid key. The Messages API is a different request
 * shape, a different auth header and a different way of constraining output, so
 * it gets its own adapter rather than a second base URL.
 *
 * Three differences that actually matter, as opposed to a dozen that are just
 * a different spelling:
 *
 *  - Auth is `x-api-key` plus a mandatory `anthropic-version`, not
 *    `Authorization: Bearer`. Omitting the version is a 400 on a request that
 *    otherwise looks correct.
 *  - There is no `response_format`. JSON is requested by declaring a tool whose
 *    input schema *is* the extraction schema, and reading the arguments back off
 *    the tool call. That is strictly better than a prose mode string: the model
 *    is forced through the schema rather than asked to respect it, so a
 *    malformed extraction becomes a missing tool call instead of a parse error
 *    on whatever prose arrived instead.
 *  - The assistant has no `system` role. The system prompt is a top-level field
 *    and is not part of the message list.
 *
 * Chat mode (escalated conversations) shares the same transport but trades the
 * extraction tools for a single `remind_admin` tool and no monetary authority.
 */

const RETRYABLE_STATUS = new Set([408, 429, 500, 502, 503, 529]);
const MAX_REPAIRS = 1;
/** A case note is a paragraph. Asking for more spends the customer's latency on prose. */
const CASE_SUMMARY_TOKENS = 220;

function isNothingToAdd(text: string): boolean {
  return text.toLowerCase() === 'nothing further to add.';
}
const MAX_ERROR_LENGTH = 500;
const ANTHROPIC_VERSION = '2023-06-01';

/**
 * The two tools the model may call in analysis mode, mirroring the OpenAI
 * adapter's union. Both are declared as first-class tools so the model is
 * pushed through the discriminator by the provider rather than asked to respect
 * a prose mode string. `ask_question` is the messenger exit; `decide_claim` is
 * the engine exit. The answer is read back off whichever tool was called.
 */
const ASK_TOOL = 'ask_question';
const DECIDE_TOOL = 'decide_claim';
const ASK_ITEMS_TOOL = 'ask_which_items';
const REMIND_TOOL = 'remind_admin';

interface MessageResponse {
  readonly content?: readonly {
    readonly type: string;
    readonly text?: string;
    /** Generated by the API, e.g. `toolu_01...`. Not the tool's name. */
    readonly id?: string;
    /** The tool that was called. This is what identifies it. */
    readonly name?: string;
    readonly input?: unknown;
  }[];
  readonly usage?: { input_tokens?: number; output_tokens?: number };
  readonly model?: string;
  readonly stop_reason?: string | null;
}

function cap(message: string): string {
  return redactSecrets(message).slice(0, MAX_ERROR_LENGTH);
}

export class AnthropicAnalyzer implements AIAnalyzer {
  readonly label: string;
  readonly model: string;
  // Constructed only with a non-empty key - `createAnalyzer` returns
  // `UnavailableAnalyzer` before reaching here otherwise - so a live provider
  // is available by construction. Availability of a *call* is still decided at
  // request time, where a 429 or a timeout is a real outcome worth recording.
  readonly available = true;
  readonly unavailableReason = null;

  private readonly candidates: readonly string[];
  /** Per-instance, so a test cannot inherit another test's view of a provider. */
  private readonly breaker: ModelCircuitBreaker;
  private readonly baseUrl: string;

  constructor(
    private readonly env: Env,
    preset: ProviderPreset,
    private readonly apiKey: string,
  ) {
    this.label = preset.label;
    this.baseUrl = (this.env.AI_BASE_URL ?? preset.baseUrl).replace(/\/+$/, '');
    this.candidates = anthropicCandidates(this.env, preset.defaultModel);
    this.breaker = new ModelCircuitBreaker(breakerConfig(this.env));
    this.model = this.candidates[0] ?? 'unknown';
  }

  /**
   * Intake: the model either asks one question or submits a complete claim.
   *
   * The repair pass reuses the first prompt verbatim and only varies the second
   * turn, because Anthropic requires the assistant turn to come before a user
   * one - the rejected extraction is the assistant's own prior reply.
   */
  async analyze(input: IntakeInput, observer: AttemptObserver): Promise<IntakeReply> {
    const budget = AbortSignal.timeout(this.env.AI_TOTAL_BUDGET_MS);
    const first = buildIntakeUser(
      input.message,
      input.order,
      input.history,
      this.env.AI_SHARE_ORDER_FACTS,
      input.allowedExits,
    );
    let complaints = 'no completion';

    for (let repair = 0; repair <= MAX_REPAIRS; repair += 1) {
      const user =
        repair === 0
          ? first
          : `${first}\n\nYour previous reply was rejected: ${complaints}. Call a tool with a valid object.`;

      const completion = await this.complete(first, user, budget, observer, input.allowedExits);
      const parsed = IntakeOutputSchema.safeParse(parseJson(completion.text));

      if (parsed.success) {
        return toIntakeReply(parsed.data, completion.model);
      }

      complaints = formatIssues(parsed.error).slice(0, 300);
      observer({
        model: completion.model,
        attempt: repair + 1,
        ok: false,
        latencyMs: 0,
        promptTokens: completion.promptTokens,
        completionTokens: completion.completionTokens,
        error: `schema: ${complaints}`,
      });

      if (budget.aborted) {
        break;
      }
    }

    throw new AiUnavailableError(
      budget.aborted
        ? `intake time budget of ${this.env.AI_TOTAL_BUDGET_MS}ms exhausted; last problem: ${complaints}`
        : `model output failed schema validation: ${complaints}`,
    );
  }

  /**
   * The case note, in one call, or null.
   *
   * The same contract as the other adapter, for the same reasons: one call, no ladder,
   * no repair pass, and every failure returns null so a missing sentence can never fail
   * a refund.
   */
  async summariseCase(input: CaseSummaryInput, observer: AttemptObserver): Promise<string | null> {
    if (input.verifiedQuotes.length === 0) {
      return null;
    }
    const budget = AbortSignal.timeout(this.env.AI_TOTAL_BUDGET_MS);
    const startedAt = Date.now();
    const model = this.candidates[0] ?? 'unknown';
    try {
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        signal: budget,
        headers: {
          'content-type': 'application/json',
          'x-api-key': this.apiKey,
          'anthropic-version': ANTHROPIC_VERSION,
        },
        body: JSON.stringify({
          model,
          max_tokens: Math.min(this.env.AI_MAX_TOKENS, CASE_SUMMARY_TOKENS),
          temperature: 0,
          system: CASE_SUMMARY_SYSTEM,
          messages: [{ role: 'user', content: buildCaseSummaryUser(input) }],
        }),
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const data = (await response.json()) as { content?: { type: string; text?: string }[] };
      const text = (data.content ?? []).find((block) => block.type === 'text')?.text ?? '';
      const parsed = CaseSummarySchema.safeParse(text);
      if (!parsed.success || isNothingToAdd(parsed.data)) {
        observer({
          model, attempt: 1, ok: false, latencyMs: Date.now() - startedAt,
          promptTokens: null, completionTokens: null, error: 'case summary rejected by validation',
        });
        return null;
      }
      observer({
        model, attempt: 1, ok: true, latencyMs: Date.now() - startedAt,
        promptTokens: null, completionTokens: null, error: null,
      });
      return parsed.data;
    } catch (error: unknown) {
      const failure = classify(error);
      observer({
        model, attempt: 1, ok: false, latencyMs: Date.now() - startedAt,
        promptTokens: null, completionTokens: null, error: failure.error,
      });
      return null;
    }
  }

  private async complete(
    firstUserMessage: string,
    user: string,
    budget: AbortSignal,
    observer: AttemptObserver,
    allowedExits?: readonly IntakeExit[],
  ): Promise<Completion> {
    const result = await runCandidates<Completion>({
      candidates: this.candidates,
      maxAttempts: this.env.AI_MAX_ATTEMPTS,
      breaker: this.breaker,
      budget,
      purpose: 'intake',
      attempt: async (model, attempt) => {
        const outcome = await this.attempt(model, attempt, firstUserMessage, user, budget, observer, allowedExits);
        return outcome.ok ? { ok: true, value: outcome.completion } : outcome;
      },
    });
    if (!result.ok) {
      throw unavailableFrom(result);
    }
    return result.value;
  }


  private async attempt(
    model: string,
    attempt: number,
    firstUserMessage: string,
    user: string,
    budget: AbortSignal,
    observer: AttemptObserver,
    allowedExits?: readonly IntakeExit[],
  ): Promise<Attempt> {
    const startedAt = Date.now();
    try {
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        signal: budget,
        headers: {
          'content-type': 'application/json',
          'x-api-key': this.apiKey,
          'anthropic-version': ANTHROPIC_VERSION,
        },
        body: JSON.stringify(
          requestBody(model, firstUserMessage, user, this.env.AI_MAX_TOKENS, allowedExits),
        ),
      });

      if (!response.ok) {
        const body = await response.text().catch(() => '');
        throw new HttpStatusError(response.status, body);
      }

      const payload = (await response.json()) as MessageResponse;
      const text = toolInputText(payload);
      if (text === null) {
        throw new EmptyCompletionError();
      }

      const usage = {
        promptTokens: payload.usage?.input_tokens ?? null,
        completionTokens: payload.usage?.output_tokens ?? null,
      };
      observer({
        model: payload.model ?? model,
        attempt,
        ok: true,
        latencyMs: Date.now() - startedAt,
        ...usage,
        error: null,
      });
      return { ok: true, completion: { text, model: payload.model ?? model, ...usage } };
    } catch (error: unknown) {
      const failure = classify(error);
      observer({
        model,
        attempt,
        ok: false,
        latencyMs: Date.now() - startedAt,
        promptTokens: null,
        completionTokens: null,
        error: failure.error,
      });
      return { ok: false, ...failure };
    }
  }

  /**
   * Chat mode for escalated conversations: a helpful conversational assistant
   * with no monetary authority. The customer's message is answered in prose,
   * or the `remind_admin` tool is called when the customer is pushing.
   */
  async chat(input: ChatInput, observer: AttemptObserver): Promise<ChatReply> {
    const budget = AbortSignal.timeout(this.env.AI_TOTAL_BUDGET_MS);
    const body = chatRequestBody(this.candidates[0] ?? 'unknown', input);
    const result = await runCandidates<ChatReply>({
      candidates: this.candidates,
      maxAttempts: this.env.AI_MAX_ATTEMPTS,
      breaker: this.breaker,
      budget,
      purpose: 'chat',
      attempt: (model, attempt) => this.chatAttempt(model, attempt, { ...body, model }, budget, observer),
    });
    if (!result.ok) {
      throw unavailableFrom(result);
    }
    return result.value;
  }

  /**
   * One chat call, reported as an outcome.
   *
   * It used to retry internally *and* let the ladder above retry it again, which
   * meant a single chat turn could cost four attempts per candidate. Retrying is the
   * ladder's job now; this returns what happened and lets it decide.
   */
  private async chatAttempt(
    model: string,
    attempt: number,
    body: Record<string, unknown>,
    budget: AbortSignal,
    observer: AttemptObserver,
  ): Promise<AttemptOutcome<ChatReply>> {
    const startedAt = Date.now();
    try {
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        signal: budget,
        headers: {
          'content-type': 'application/json',
          'x-api-key': this.apiKey,
          'anthropic-version': ANTHROPIC_VERSION,
        },
        body: JSON.stringify(body),
      });

      if (!response.ok) {
        const failedBody = await response.text().catch(() => '');
        throw new HttpStatusError(response.status, failedBody);
      }

      const data = (await response.json()) as MessageResponse;
      const answer = chatAnswer(data, model);
      observer({
        model,
        attempt,
        ok: answer !== null,
        latencyMs: Date.now() - startedAt,
        promptTokens: data.usage?.input_tokens ?? null,
        completionTokens: data.usage?.output_tokens ?? null,
        error: answer === null ? 'chat reply carried neither text nor a tool call' : null,
      });
      // A reply with no text and no tool call is the empty-completion case again, in
      // chat clothing, and it is not retryable: the model answered, and its answer
      // was nothing.
      return answer === null
        ? { ok: false, error: 'chat reply carried neither text nor a tool call', retryable: false }
        : { ok: true, value: answer };
    } catch (error: unknown) {
      const failure = classify(error);
      observer({
        model,
        attempt,
        ok: false,
        latencyMs: Date.now() - startedAt,
        promptTokens: null,
        completionTokens: null,
        error: failure.error,
      });
      return { ok: false, ...failure };
    }
  }
}

interface Completion {
  readonly text: string;
  readonly model: string;
  readonly promptTokens: number | null;
  readonly completionTokens: number | null;
}

type Attempt =
  | { readonly ok: true; readonly completion: Completion }
  | { readonly ok: false; readonly error: string; readonly retryable: boolean };

interface Failure {
  readonly error: string;
  readonly retryable: boolean;
}

/** A 200 with no tool call: the model answered in prose instead of the schema. */
class EmptyCompletionError extends Error {
  constructor() {
    super('model replied without calling the extraction tool');
    this.name = 'EmptyCompletionError';
  }
}

/**
 * The body of one Messages call.
 *
 * The repair pass reuses the first prompt verbatim and only varies the second
 * turn, because Anthropic requires the assistant turn to come before a user one -
 * the original extraction is the assistant's own prior reply.
 */
function requestBody(
  model: string,
  firstUserMessage: string,
  user: string,
  maxTokens: number,
  allowedExits: readonly IntakeExit[] | undefined,
): Record<string, unknown> {
  const repairTurn = user !== firstUserMessage;
  return {
    model,
    max_tokens: maxTokens,
    // Low enough to keep the extraction reproducible. A claim that reads the
    // same message two different ways is a claim nobody can audit.
    temperature: 0,
    system: INTAKE_SYSTEM,
    // `any` rather than the single-tool `tool` choice: the model must call one of
    // the tools but gets to pick which - exactly the ask-or-decide discriminator
    // the engine is built around, now with a third exit for the item picker.
    // The tool list is the enforced gate on this wire format: a tool that is not
    // offered cannot be called, so a closed exit is closed rather than merely
    // discouraged.
    tools:
      allowedExits === undefined || allowedExits.includes('ask_items')
        ? [askTool(), askItemsTool(), decideTool()]
        : [askTool(), decideTool()],
    tool_choice: { type: 'any' },
    messages: repairTurn
      ? [
          { role: 'user', content: firstUserMessage },
          { role: 'assistant', content: 'I will call a tool.' },
          { role: 'user', content: user },
        ]
      : [{ role: 'user', content: firstUserMessage }],
  };
}

function askTool(): { name: string; description: string; input_schema: object } {
  return {
    name: ASK_TOOL,
    description: 'Ask the customer exactly one clarifying question for the one missing detail.',
    input_schema: z.toJSONSchema(z.object({ question: z.string().min(1).max(400) })),
  };
}

/**
 * The picker's tool.
 *
 * Carries ids and nothing else - no question text, because the answer is a set of
 * buttons and a caption would be a second interface competing with the first.
 * The ids are a hint; `retrieval/itemPicker.ts` re-checks them against the order
 * and the server decides whether to ask at all.
 */
function askItemsTool(): { name: string; description: string; input_schema: object } {
  return {
    name: ASK_ITEMS_TOOL,
    description:
      'Ask the customer which line of the order their problem is about. Use only when they ' +
      'have described a problem but have not said which item it concerns. Names the item ids ' +
      'you could not tell apart, or none if you could not narrow it down.',
    input_schema: z.toJSONSchema(AskItemsSchema),
  };
}

function decideTool(): { name: string; description: string; input_schema: object } {
  return {
    name: DECIDE_TOOL,
    description: 'Submit the structured refund claim read from the conversation to the policy engine.',
    input_schema: z.toJSONSchema(CompleteSchema),
  };
}

function remindTool(): { name: string; description: string; input_schema: object } {
  return {
    name: REMIND_TOOL,
    description: 'Notify the human agent that the customer is waiting or pushing for a response.',
    input_schema: { type: 'object', properties: {}, additionalProperties: false },
  };
}

/**
 * The Messages body for one chat-mode turn.
 *
 * `tool_choice: auto` rather than the analysis adapter's `any`, because the
 * answer here is usually prose. Forcing a tool would make the model call
 * `remind_admin` on every message, which is precisely the opposite of the point
 * of the tool.
 */
function chatRequestBody(model: string, input: ChatInput, maxTokens = 4096): Record<string, unknown> {
  const historyText = input.history.map((line) => `${line.role}: ${line.text}`).join('\n');
  const body: Record<string, unknown> = {
    model,
    max_tokens: maxTokens,
    temperature: 0.7,
    system: CHAT_SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Customer message: ${input.message}\n\nConversation history:\n${historyText}\n\nAvailable tools: ${input.tools.map((t) => t.name).join(', ')}`,
      },
    ],
  };
  if (input.tools.length > 0) {
    body.tools = [remindTool()];
    body.tool_choice = { type: 'auto' };
  }
  return body;
}

/**
 * Reads the turn's answer off the response: a `remind_admin` tool call if the
 * model reached for one, otherwise its prose. Null means nothing usable came
 * back, which is a miss worth another attempt rather than a reply to send.
 */
function chatAnswer(payload: MessageResponse, model: string): ChatReply | null {
  const toolUse = payload.content?.find((block) => block.type === 'tool_use');
  if (toolUse !== undefined && toolUse.name === REMIND_TOOL) {
    return { kind: 'tool_call', tool: REMIND_TOOL, model };
  }

  const text = payload.content?.find((block) => block.type === 'text')?.text ?? '';
  return text.trim().length === 0 ? null : { kind: 'text', text, model };
}

/**
 * The tool call, normalised to the union shape, or null when none was made.
 *
 * Each tool's input is bare - `{question}`, `{candidates}`, or the extraction
 * itself - so the discriminator the engine validates is put back on here. That
 * keeps the downstream path "text in, Zod out" exactly as it is for the OpenAI
 * adapter, and keeps one schema the authority on what a reply may contain rather
 * than two shapes that can drift apart.
 *
 * Matched on the block's `name`, never its `id`: a real `tool_use` block has a
 * generated `id`, and matching on it would accept any tool whose id happened to
 * look like one of ours.
 */
function toolInputText(payload: MessageResponse): string | null {
  for (const block of payload.content ?? []) {
    if (block.type !== 'tool_use') {
      continue;
    }
    const normalised = normaliseToolInput(String(block.name), block.input);
    if (normalised !== null) {
      return normalised;
    }
  }
  return null;
}

function normaliseToolInput(name: string, raw: unknown): string | null {
  const input = typeof raw === 'object' && raw !== null ? raw : {};
  if (name === ASK_ITEMS_TOOL) {
    const { candidates } = input as { candidates?: unknown };
    return JSON.stringify({ action: 'ask_items', candidates });
  }
  if (name === ASK_TOOL) {
    const { question } = input as { question?: unknown };
    return JSON.stringify({ action: 'ask', question });
  }
  if (name === DECIDE_TOOL) {
    return JSON.stringify({ action: 'decide', ...input });
  }
  return null;
}

/**
 * An HTTP error response, with the status kept as a field.
 *
 * Its own class rather than a cast onto `Error`, so the retry decision reads the
 * status off a known shape instead of reaching through `unknown` for it.
 */
class HttpStatusError extends Error {
  constructor(
    readonly status: number,
    readonly body: string,
  ) {
    super(`HTTP ${status}: ${body}`);
    this.name = 'HttpStatusError';
  }
}

/**
 * Classifies a failure, reusing the same rules the OpenAI adapter applies.
 *
 * Retryable means "a different model, or the same model in a moment, might work":
 * rate limits, timeouts and 5xx. A 400 is not retryable, because the request is
 * wrong and repeating it verbatim will be wrong in the same way - which is the
 * usual symptom of a model id this account cannot invoke.
 */
function classify(error: unknown): Failure {
  if (error instanceof EmptyCompletionError) {
    return { error: error.message, retryable: false };
  }
  if (error instanceof HttpStatusError) {
    return { error: cap(`HTTP ${error.status}: ${error.body}`), retryable: RETRYABLE_STATUS.has(error.status) };
  }
  if (error instanceof Error && error.name === 'AbortError') {
    return { error: 'aborted: analysis time budget exhausted', retryable: false };
  }
  if (error instanceof Error && error.name === 'TimeoutError') {
    return { error: cap(`timeout: ${error.message}`), retryable: true };
  }
  return {
    error: cap(`unexpected: ${error instanceof Error ? error.message : String(error)}`),
    retryable: false,
  };
}

/**
 * The validated wire object as an `IntakeReply`.
 *
 * The claim is re-parsed through the extraction schema on the way in rather than
 * spread out of the wire object, because that parse is what strips the `action`
 * discriminator and anything else the model invented: what the engine receives is
 * the extraction schema and nothing else.
 */
function toIntakeReply(data: IntakeOutput, model: string): IntakeReply {
  if (data.action === 'ask_items') {
    return { kind: 'ask_items', candidates: data.candidates, model };
  }
  if (data.action === 'ask') {
    return { kind: 'question', question: data.question, model };
  }
  return { kind: 'complete', extraction: ClaimExtractionSchema.parse(data), model };
}

function formatIssues(error: z.ZodError): string {
  return error.issues
    .slice(0, 5)
    .map((issue) => `${issue.path.join('.') || '(root)'} ${issue.message}`)
    .join('; ');
}

/**
 * The configured model first, then any fallbacks, de-duplicated.
 *
 * The model list is provider-specific, so a fallback id that is not an Anthropic
 * model is simply a 404 that the next candidate moves past. The adapter does not
 * second-guess the operator's list.
 */
function anthropicCandidates(env: Env, defaultModel: string): string[] {
  const primary = env.AI_MODEL ?? defaultModel;
  return [...new Set([primary, ...fallbackModels(env)])].filter((model) => model.length > 0);
}