import { z } from 'zod';
import { setTimeout as sleep } from 'node:timers/promises';
import { fallbackModels, type Env, type ProviderPreset } from '../config/env.js';
import { redactSecrets } from '../lib/redact.js';
import { buildExtractionUser, EXTRACTION_SYSTEM } from './prompts.js';
import { ExtractionOutputSchema } from './schemas.js';
import { parseJson } from './json.js';
import {
  AiUnavailableError,
  type AIAnalyzer,
  type AnalyzerInput,
  type AnalyzerResult,
  type AttemptObserver,
} from './analyzer.js';

/**
 * The Anthropic adapter.
 *
 * It exists because Anthropic has no OpenAI-compatible endpoint. `POST
 * /v1/chat/completions` is not served by `api.anthropic.com`, so pointing the
 * OpenAI client at it produces a 404 on a URL that is not wrong so much as
 * inoffensible - and a 404 reads, to everyone except the person who wrote this
 * comment, exactly like an invalid key. The Messages API is a different request
 * shape, a different auth header and a different way of constraining output, so
 * it gets its own adapter rather than a second base URL.
 *
 * Three differences that actually matter, as opposed to a dozen that are just
 * a different spelling:
 *
 *  - Auth is `x-api-key` plus a mandatory `anthropic-version`, not
 *    `Authorization: Bearer`. Omitting the version is a 400 on a request that
 *    otherwise looks correct.
 *  - There is no `response_format`. JSON is requested by declaring a tool whose
 *    input schema *is* the extraction schema, and reading the arguments back off
 *    the tool call. That is strictly better than a prose mode string: the model
 *    is forced through the schema rather than asked to respect it, so a
 *    malformed extraction becomes a missing tool call instead of a parse error
 *    on whatever prose arrived instead.
 *  - The assistant has no `system` role. The system prompt is a top-level field
 *    and is not part of the message list.
 */

const RETRYABLE_STATUS = new Set([408, 429, 500, 502, 503, 529]);
const BACKOFF_MS = [400, 1200] as const;
const MAX_REPAIRS = 1;
const MAX_ERROR_LENGTH = 500;
const ANTHROPIC_VERSION = '2023-06-01';

/** The tool the model must call instead of answering in prose. */
const TOOL_NAME = 'record_refund_claim';

interface MessageResponse {
  readonly content?: readonly {
    readonly type: string;
    readonly text?: string;
    /** Generated by the API, e.g. `toolu_01...`. Not the tool's name. */
    readonly id?: string;
    /** The tool that was called. This is what identifies it. */
    readonly name?: string;
    readonly input?: unknown;
  }[];
  readonly usage?: { input_tokens?: number; output_tokens?: number };
  readonly model?: string;
  readonly stop_reason?: string | null;
}

function cap(message: string): string {
  return redactSecrets(message).slice(0, MAX_ERROR_LENGTH);
}

export class AnthropicAnalyzer implements AIAnalyzer {
  readonly label: string;
  readonly model: string;

  private readonly candidates: readonly string[];
  private readonly baseUrl: string;

  constructor(
    private readonly env: Env,
    preset: ProviderPreset,
    private readonly apiKey: string,
  ) {
    this.label = preset.label;
    this.baseUrl = (this.env.AI_BASE_URL ?? preset.baseUrl).replace(/\/+$/, '');
    this.candidates = anthropicCandidates(this.env, preset.defaultModel);
    this.model = this.candidates[0] ?? 'unknown';
  }

  async analyze(input: AnalyzerInput, observer: AttemptObserver): Promise<AnalyzerResult> {
    const budget = AbortSignal.timeout(this.env.AI_TOTAL_BUDGET_MS);
    const base = buildExtractionUser(input.message, input.order, this.env.AI_SHARE_ORDER_FACTS);
    let complaints = 'no completion';

    for (let repair = 0; repair <= MAX_REPAIRS; repair += 1) {
      const user =
        repair === 0
          ? base
          : `${base}\n\nYour previous reply was rejected: ${complaints}. Call the tool with a valid object.`;

      const completion = await this.complete(base, user, budget, observer);
      const parsed = ExtractionOutputSchema.safeParse(parseJson(completion.text));

      if (parsed.success) {
        return toResult(parsed.data, completion.model);
      }

      complaints = formatIssues(parsed.error).slice(0, 300);
      observer({
        model: completion.model,
        attempt: repair + 1,
        ok: false,
        latencyMs: 0,
        promptTokens: completion.promptTokens,
        completionTokens: completion.completionTokens,
        error: `schema: ${complaints}`,
      });

      if (budget.aborted) {
        break;
      }
    }

    throw new AiUnavailableError(
      budget.aborted
        ? `analysis time budget of ${this.env.AI_TOTAL_BUDGET_MS}ms exhausted; last problem: ${complaints}`
        : `model output failed schema validation: ${complaints}`,
    );
  }

  /**
   * The repair pass reuses the first prompt verbatim and only varies the second
   * turn, because Anthropic requires the assistant turn to come before a user
   * one - the original extraction is the assistant's own prior reply.
   */
  private async complete(
    firstUserMessage: string,
    user: string,
    budget: AbortSignal,
    observer: AttemptObserver,
  ): Promise<Completion> {
    const failures: string[] = [];

    for (const model of this.candidates) {
      for (let attempt = 1; attempt <= this.env.AI_MAX_ATTEMPTS; attempt += 1) {
        if (budget.aborted) {
          throw new AiUnavailableError(`analysis time budget exhausted after ${failures.length} attempt(s)`);
        }

        const outcome = await this.attempt(model, attempt, firstUserMessage, user, budget, observer);
        if (outcome.ok) {
          return outcome.completion;
        }
        failures.push(`${model}#${attempt} ${outcome.error}`);

        if (attempt < this.env.AI_MAX_ATTEMPTS && outcome.retryable) {
          await backoff(attempt, budget);
        } else if (!outcome.retryable) {
          break;
        }
      }
    }

    throw new AiUnavailableError(
      cap(`all ${this.candidates.length} anthropic model(s) failed after ${failures.length} attempt(s): ${failures.join(' | ')}`),
    );
  }

  private async attempt(
    model: string,
    attempt: number,
    firstUserMessage: string,
    user: string,
    budget: AbortSignal,
    observer: AttemptObserver,
  ): Promise<Attempt> {
    const startedAt = Date.now();
    try {
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        signal: budget,
        headers: {
          'content-type': 'application/json',
          'x-api-key': this.apiKey,
          'anthropic-version': ANTHROPIC_VERSION,
        },
        body: JSON.stringify(requestBody(model, firstUserMessage, user, this.env.AI_MAX_TOKENS)),
      });

      if (!response.ok) {
        const body = await response.text().catch(() => '');
        throw new HttpStatusError(response.status, body);
      }

      const payload = (await response.json()) as MessageResponse;
      const text = toolInputText(payload);
      if (text === null) {
        throw new EmptyCompletionError();
      }

      const usage = {
        promptTokens: payload.usage?.input_tokens ?? null,
        completionTokens: payload.usage?.output_tokens ?? null,
      };
      observer({
        model: payload.model ?? model,
        attempt,
        ok: true,
        latencyMs: Date.now() - startedAt,
        ...usage,
        error: null,
      });
      return { ok: true, completion: { text, model: payload.model ?? model, ...usage } };
    } catch (error: unknown) {
      const failure = classify(error);
      observer({
        model,
        attempt,
        ok: false,
        latencyMs: Date.now() - startedAt,
        promptTokens: null,
        completionTokens: null,
        error: failure.error,
      });
      return { ok: false, ...failure };
    }
  }
}

interface Completion {
  readonly text: string;
  readonly model: string;
  readonly promptTokens: number | null;
  readonly completionTokens: number | null;
}

type Attempt =
  | { readonly ok: true; readonly completion: Completion }
  | { readonly ok: false; readonly error: string; readonly retryable: boolean };

interface Failure {
  readonly error: string;
  readonly retryable: boolean;
}

/** A 200 with no tool call: the model answered in prose instead of the schema. */
class EmptyCompletionError extends Error {
  constructor() {
    super('model replied without calling the extraction tool');
    this.name = 'EmptyCompletionError';
  }
}

/**
 * The tool whose input schema is the extraction schema.
 *
 * Built from Zod so the prompt and the validator cannot drift. Anthropic accepts
 * a JSON Schema for `input_schema`, and `z.toJSONSchema` produces one, which is
 * the only reason the OpenAI adapter's schema description is reusable here.
 */
/**
 * The body of one Messages call.
 *
 * The repair pass reuses the first prompt verbatim and only varies the second
 * turn, because Anthropic requires the assistant turn to come before a user one -
 * the original extraction is the assistant's own prior reply.
 */
function requestBody(
  model: string,
  firstUserMessage: string,
  user: string,
  maxTokens: number,
): Record<string, unknown> {
  const repairTurn = user !== firstUserMessage;
  return {
    model,
    max_tokens: maxTokens,
    // Low enough to keep the extraction reproducible. A claim that reads the
    // same message two different ways is a claim nobody can audit.
    temperature: 0,
    system: EXTRACTION_SYSTEM,
    tools: [extractionTool()],
    tool_choice: { type: 'tool', name: TOOL_NAME },
    messages: repairTurn
      ? [
          { role: 'user', content: firstUserMessage },
          { role: 'assistant', content: 'I will record the claim.' },
          { role: 'user', content: user },
        ]
      : [{ role: 'user', content: firstUserMessage }],
  };
}

function extractionTool(): { name: string; description: string; input_schema: object } {
  return {
    name: TOOL_NAME,
    description: 'Record the structured refund claim found in the customer message.',
    input_schema: z.toJSONSchema(ExtractionOutputSchema),
  };
}

/** The tool call's arguments, or null when the model did not make one. */
function toolInputText(payload: MessageResponse): string | null {
  for (const block of payload.content ?? []) {
    if (block.type === 'tool_use' && block.name === TOOL_NAME) {
      // `input` is the already-decoded object. Re-serialising it means the
      // downstream path is identical to the OpenAI adapter's: text in, Zod out.
      return JSON.stringify(block.input ?? null);
    }
  }
  return null;
}

/**
 * An HTTP error response, with the status kept as a field.
 *
 * Its own class rather than a cast onto `Error`, so the retry decision reads the
 * status off a known shape instead of reaching through `unknown` for it.
 */
class HttpStatusError extends Error {
  constructor(
    readonly status: number,
    readonly body: string,
  ) {
    super(`HTTP ${status}: ${body}`);
    this.name = 'HttpStatusError';
  }
}

/**
 * Classifies a failure, reusing the same rules the OpenAI adapter applies.
 *
 * Retryable means "a different model, or the same model in a moment, might work":
 * rate limits, timeouts and 5xx. A 400 is not retryable, because the request is
 * wrong and repeating it verbatim will be wrong in the same way - which is the
 * usual symptom of a model id this account cannot invoke.
 */
function classify(error: unknown): Failure {
  if (error instanceof EmptyCompletionError) {
    return { error: error.message, retryable: false };
  }
  if (error instanceof HttpStatusError) {
    return { error: cap(`HTTP ${error.status}: ${error.body}`), retryable: RETRYABLE_STATUS.has(error.status) };
  }
  if (error instanceof Error && error.name === 'AbortError') {
    return { error: 'aborted: analysis time budget exhausted', retryable: false };
  }
  if (error instanceof Error && error.name === 'TimeoutError') {
    return { error: cap(`timeout: ${error.message}`), retryable: true };
  }
  return {
    error: cap(`unexpected: ${error instanceof Error ? error.message : String(error)}`),
    retryable: false,
  };
}

async function backoff(attempt: number, budget: AbortSignal): Promise<void> {
  const last = BACKOFF_MS.length - 1;
  const wait = BACKOFF_MS[Math.min(attempt - 1, last)] ?? BACKOFF_MS[last];
  try {
    await sleep(wait, undefined, { signal: budget });
  } catch (error: unknown) {
    if (budget.aborted) {
      throw new AiUnavailableError('analysis time budget exhausted while backing off');
    }
    throw error;
  }
}

function toResult(data: z.infer<typeof ExtractionOutputSchema>, model: string): AnalyzerResult {
  const { suggestedDecision, suggestedAmountCents, ...extraction } = data;
  return {
    extraction,
    proposal: {
      suggestedDecision,
      suggestedAmountCents,
      confidence: extraction.confidence,
      reason: extraction.reason,
      model,
    },
    model,
  };
}

function formatIssues(error: z.ZodError): string {
  return error.issues
    .slice(0, 5)
    .map((issue) => `${issue.path.join('.') || '(root)'} ${issue.message}`)
    .join('; ');
}

/**
 * The configured model first, then any fallbacks, de-duplicated.
 *
 * The model list is provider-specific, so a fallback id that is not an Anthropic
 * model is simply a 404 that the next candidate moves past. The adapter does not
 * second-guess the operator's list.
 */
function anthropicCandidates(env: Env, defaultModel: string): string[] {
  const primary = env.AI_MODEL ?? defaultModel;
  return [...new Set([primary, ...fallbackModels(env)])].filter((model) => model.length > 0);
}
