import { SCENARIOS } from '@refund/shared';
import { processRefundRequest, type PipelineDeps } from '../orchestrator.js';
import { persistDecision } from './persistDecision.js';
import { rowFromDecision } from './requestRow.js';
import { settleRefund } from './refundLedger.js';
import type { Db } from './connection.js';
import { findCustomer } from './sql.js';

/**
 * A little decision history, so the console opens onto a product rather than an
 * empty table.
 *
 * Unlike the rest of the seed data, these rows are not written - they are
 * produced. Each canonical scenario is submitted through the same
 * `processRefundRequest` the live chat route uses, so a row in the demo history
 * has a real trace, real grounding, real injection scan and a real response
 * text, generated by whatever analyzer the deployment is configured with (a
 * model in production, the local heuristic in tests). The only hand-written
 * parts are the fixed request ids and the staggered timestamps.
 *
 * This is why it takes the pipeline deps as an argument rather than building
 * them itself: the caller (index.ts at boot, a test in the suite) decides which
 * analyzer the history is produced by.
 *
 * It runs from `index.ts` on a fresh database only. Deliberately *not* called
 * from `seedDatabase`, because the tests share that one and a seeded reservation
 * would change what R-06b is supposed to decide.
 */

/** Scenarios chosen to cover each outcome the dashboard needs to display. */
const HISTORY: readonly { readonly scenarioId: string; readonly settled: boolean }[] = [
  { scenarioId: 'S-01', settled: true },
  { scenarioId: 'S-04', settled: false },
  { scenarioId: 'S-02', settled: false },
  { scenarioId: 'S-13', settled: false },
  { scenarioId: 'S-05', settled: false },
];

/** Spaced out over the last few days so the "recent" list has a real shape. */
function createdAt(now: Date, daysAgo: number, hour: number): string {
  const at = new Date(now.getTime() - daysAgo * 86_400_000);
  at.setUTCHours(hour, (daysAgo * 7) % 60, 0, 0);
  return at.toISOString();
}

export interface SeededHistory {
  /** Rows persisted. */
  readonly created: number;
  /**
   * Scenarios the pipeline answered with a clarifying question instead of a
   * decision. A run that asks nothing is not a request - it is dialogue - so it
   * can never become a history row.
   */
  readonly asked: number;
}

export async function seedRequestHistory(db: Db, now: Date, pipeline: PipelineDeps): Promise<SeededHistory> {
  let created = 0;
  let asked = 0;

  for (const [index, entry] of HISTORY.entries()) {
    const scenario = SCENARIOS.find((candidate) => candidate.id === entry.scenarioId);
    // S-09 deliberately points at an order that does not exist; a history row
    // with no order would have no balance to reason about, so it is skipped.
    if (scenario === undefined || scenario.orderId === null) {
      continue;
    }
    if (findCustomer(db, scenario.customer.key, now) === null) {
      continue;
    }
    // A fixed id per scenario, so a restart cannot duplicate the history and a
    // reviewer can find the row they saw last time.
    const requestId = `seed-${scenario.id.toLowerCase()}`;
    const existing = db
      .prepare('SELECT 1 AS present FROM refund_requests WHERE id = ?')
      .get(requestId);
    if (existing !== undefined) {
      continue;
    }

    // The pipeline runs at `now` so the order-age windows are exactly the ones
    // the scenario was written to hit; the row is then back-dated with its
    // display timestamp.
    const at = createdAt(now, HISTORY.length - index, 9 + index);
    const result = await processRefundRequest(db, pipeline, {
      requestId,
      customerId: scenario.customer.key,
      orderId: scenario.orderId,
      message: scenario.message,
      itemIds: [],
      now,
    });
    if (result.stage === 'asked') {
      asked += 1;
      continue;
    }

    const row = rowFromDecision({
      requestId,
      customerId: scenario.customer.key,
      message: scenario.message,
      now: new Date(at),
      scenarioId: scenario.id,
      result,
    });
    const persisted = persistDecision(db, row, {
      orderId: row.orderId,
      customerId: row.customerId,
      now: new Date(at),
    });

    // One is left awaiting verification on purpose, so the review queue has
    // something in it the moment somebody opens the console.
    if (entry.settled && persisted.reservationId !== null) {
      // Through the ledger, not around it. A hand-written UPDATE that
      // satisfied the status check but skipped `verified_at` is exactly the
      // row the table's constraints exist to refuse, and the table refused
      // it. Settling is how a person verifies a claim, so the seeded person
      // is named in the row.
      settleRefund(db, persisted.reservationId, 'seed@refund.test', new Date(at));
    }
    created += 1;
  }

  return { created, asked };
}